### ISSUE TITLE
Flask Server

### ISSUE THREAD

**Issue by ajhamwood** [bearfoot-bandits/uqhackathon#1]
Nikhil

**Comment by ajhamwood** [comment]
On ubuntu, here is how I set up flask ( https://linuxize.com/post/how-to-install-flask-on-ubuntu-18-04/ ):

$ sudo apt install python3-venv
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install Flask
(venv) $ export FLASK_APP=app
(venv) $ flask run

with uqhackathon/app.py:

from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello World!'

**Comment by bearfoot-bandits** [comment]
Completed
